############# Hungarian navigation ##############

# main menu
[[main]]
name = "Főoldal"
url = "/hu/"
weight = 1

[[main]]
name = "Rólam"
url = "/hu/about/"
weight = 2

[[main]]
name = "Blog"
url = "/hu/blog/"
weight = 3

[[main]]
name = "Irodalmi munkásság"
weight = 4

[[main]]
parent = "Irodalmi munkásság"
name = "Műfordítás és szerkesztés"
url = "/hu/translation-and-editing/"
weight = 1

[[main]]
parent = "Irodalmi munkásság"
name = "Publikációk"
url = "/hu/publications/"
weight = 2

[[main]]
name = "Szaklektorálás"
weight = 5

[[main]]
parent = "Szaklektorálás"
name = "Kötésminták lektorálása"
url = "/hu/knitting-technical-editing/"
weight = 1

[[main]]
parent = "Szaklektorálás"
name = "Portfólió"
url = "/hu/te-portfolio/"
weight = 2

[[main]]
parent = "Szaklektorálás"
name = "Magánprojektjeim"
url = "/hu/my-knitting-projects/"
weight = 3


# footer menu

[[footer]]
name = "Főoldal"
url = "/hu/"
weight = 1

[[footer]]
name = "Rólam"
url = "/hu/about/"
weight = 2

[[footer]]
name = "Blog"
url = "/hu/blog/"
weight = 3

[[footer]]
name = "Műfordítás és szerkesztés"
url = "/hu/translation-and-editing/"
weight = 4

[[footer]]
name = "Kötésminták lektorálása"
url = "/hu/knitting-technical-editing/"
weight = 5

[[footer]]
name = "Lektorált mintáim"
url = "/hu/te-portfolio/"
weight = 6

[[footer]]
name = "Magánprojektjeim"
url = "/hu/my-knitting-projects/"
weight = 7

[[footer]]
name = "Publikációk"
url = "/hu/publications/"
weight = 8

[[footer]]
name = "Hírlevél"
url = "https://yarnboundtales.substack.com/"
weight = 9

[[footer]]
name = "Adatkezelési tájékoztató"
url = "/hu/privacy-policy/"
weight = 10

[[footer]]
name = "Impresszum"
url = "/hu/impressum/"
weight = 11